// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFkzrAJc-tRyzOyXJ72NQM6J6IGM5w7FE',
    appId: '1:370105776817:web:5b16449a6aa671826a4090',
    messagingSenderId: '370105776817',
    projectId: 'pingo-2dacb',
    authDomain: 'pingo-2dacb.firebaseapp.com',
    storageBucket: 'pingo-2dacb.appspot.com',
    measurementId: 'G-ZFMTPF45NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTcDYigrunT25I9iuLmwdA9kfLTat4BE',
    appId: '1:370105776817:android:12cde7635d74157e6a4090',
    messagingSenderId: '370105776817',
    projectId: 'pingo-2dacb',
    storageBucket: 'pingo-2dacb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVMDcVyaOmhqP7R5Z475SV1YUxOEXKHo',
    appId: '1:370105776817:ios:38ef5f73f87ece486a4090',
    messagingSenderId: '370105776817',
    projectId: 'pingo-2dacb',
    storageBucket: 'pingo-2dacb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVMDcVyaOmhqP7R5Z475SV1YUxOEXKHo',
    appId: '1:370105776817:ios:5c38de9f45cfcaee6a4090',
    messagingSenderId: '370105776817',
    projectId: 'pingo-2dacb',
    storageBucket: 'pingo-2dacb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
